namespace bash_royale;

public enum UnitType
{
    Knight,
    Tower,
    Castle,
    Giant,
    Archer,
    Goblin,
    Wizard,
    HogRider,
    Barbarian,
    Musketeer,
    MiniPekka,
    Valkyrie,
    Skeleton,
    Dragon,

}
public record UnitInfo(
    UnitType Type,
    string Name,
    
    int MaxHealth,
    int AttackRange,
    int AggroRange,
    int TicksPerAttack,
    bool ranged,
    IUnitBehaviour NeutralBehaviour,
    IUnitBehaviour ChaseBehaviour,
    IUnitBehaviour AttackBehaviour,
    Vector2Int Size,
    MovementLayer Layer,
    bool IsBuilding = false,
    bool targetsBuildingsOnly = false);

public static class UnitInfos
{
    public static UnitInfo GetUnitInfo(UnitType unitType)
    {
        return unitType switch
        {
            UnitType.Knight => new UnitInfo(
                UnitType.Knight,
                "Knight",
                700,
                1,
                6,
                20,
                false,
                new WalkForwards(5),
                new ChaseBehaviour(5), 
                new AttackBehaviour(75),
                new Vector2Int(1,1),
                MovementLayer.Ground),
            UnitType.Tower => new UnitInfo(
                UnitType.Tower,
                "Tower",
                2000,
                5,
                5,
                10,
                true,
                new DoNothing(),
                new DoNothing(),
                new AttackBehaviour(5),
                new Vector2Int(1,1),
                MovementLayer.Ground,
                true),
            UnitType.Castle => new UnitInfo(
                UnitType.Castle,
                "Castle",
                3000,
                5,
                5,
                10,
                true,
                new DoNothing(),
                new DoNothing(),
                new AttackBehaviour(5),
                new Vector2Int(1,1),
                MovementLayer.Ground,
                true),
                UnitType.Giant => new UnitInfo(
                UnitType.Giant,
                "Giant",
                1500,
                1,
                5,
                20,
                false,
                new WalkForwards(5),
                new ChaseBehaviour(5), 
                new AttackBehaviour(75),
                new Vector2Int(2,2),
                MovementLayer.Ground,
                false,
                true),
                UnitType.Archer => new UnitInfo(
                UnitType.Archer,
                "Archer",
                500,
                5,
                10,
                10,
                true,
                new WalkForwards(10),
                new ChaseBehaviour(5), 
                new AttackBehaviour(75),
                new Vector2Int(1,1),
                MovementLayer.Ground),
                UnitType.Goblin => new UnitInfo(
                UnitType.Goblin,
                "Goblin",
                200,
                1,
                8,
                5,
                false,
                new WalkForwards(12),
                new ChaseBehaviour(5), 
                new AttackBehaviour(75),
                new Vector2Int(1,1),
                MovementLayer.Ground),
                UnitType.Wizard => new UnitInfo(
                UnitType.Wizard,
                "Wizard",
                600,
                5,
                5,
                10,
                true,
                new WalkForwards(5),
                new ChaseBehaviour(5), 
                new AttackBehaviour(75),
                new Vector2Int(1,1),
                MovementLayer.Ground),
                UnitType.HogRider => new UnitInfo(
                UnitType.HogRider,
                "Horde",
                800,
                1,
                3,
                10,
                false,
                new WalkForwards(15),
                new ChaseBehaviour(15), 
                new AttackBehaviour(75),
                new Vector2Int(1,1),
                MovementLayer.Ground),
                UnitType.Barbarian => new UnitInfo(
                UnitType.Barbarian,
                "Barbarian",
                900,
                1,
                7,
                18,
                false,
                new WalkForwards(7),
                new ChaseBehaviour(7),
                new AttackBehaviour(90),
                new Vector2Int(1,1),
                MovementLayer.Ground),
                UnitType.Musketeer => new UnitInfo(
                UnitType.Musketeer,
                "Musketeer",
                600,
                6,
                9,
                12,
                true,
                new WalkForwards(7),
                new ChaseBehaviour(5),
                new AttackBehaviour(100),
                new Vector2Int(1,1),
                MovementLayer.Ground),
                UnitType.MiniPekka => new UnitInfo(
                UnitType.MiniPekka,
                "Mini Pekka",
                1000,
                1,
                4,
                30,
                false,
                new WalkForwards(13),
                new ChaseBehaviour(13),
                new AttackBehaviour(300),
                new Vector2Int(1,1),
                MovementLayer.Ground),
                UnitType.Valkyrie => new UnitInfo(
                UnitType.Valkyrie,
                "Valkyrie",
                1100,
                1,
                6,
                22,
                false,
                new WalkForwards(8),
                new ChaseBehaviour(8),
                new AttackBehaviour(120),
                new Vector2Int(1,1),
                MovementLayer.Ground),
                UnitType.Skeleton => new UnitInfo(
                UnitType.Skeleton,
                "Skeleton",
                120,
                1,
                8,
                8,
                false,
                new WalkForwards(14),
                new ChaseBehaviour(14),
                new AttackBehaviour(40),
                new Vector2Int(1,1),
                MovementLayer.Ground),
                UnitType.Dragon => new UnitInfo(
                UnitType.Dragon,
                "Baby Dragon",
                800,
                4,
                8,
                16,
                true,
                new WalkForwards(9),
                new ChaseBehaviour(9),
                new AttackBehaviour(110),
                new Vector2Int(1,1),
                MovementLayer.Air),
                
            _ => throw new ArgumentOutOfRangeException(nameof(unitType), unitType, null)
        };
    }
}