namespace bash_royale;

public enum UnitType
{
    Knight,
    Tower,
    Castle,
    Giant,
    Archer,
    Goblin,
    Wizard,
    HogRider,
    BabyDragon,
    Barbarian,
    Musketeer,
    MiniPekka,
    Valkyrie,
    Dragon,
    Skeleton,
    Cannon,
    GoblinCage,
    Brawler,
    Pekka,

}
public record UnitInfo(
    UnitType Type,
    string Name,
    
    int MaxHealth,
    int AttackRange,
    int AggroRange,
    int TicksPerAttack,
    bool ranged,
    IUnitBehaviour NeutralBehaviour,
    IUnitBehaviour ChaseBehaviour,
    IUnitBehaviour AttackBehaviour,
    Vector2Int Size,
    MovementLayer Layer,
    bool IsBuilding = false,
    bool targetsBuildingsOnly = false);

public static class UnitInfos
{
    public static UnitInfo GetUnitInfo(UnitType unitType)
    {
        return unitType switch
        {
            UnitType.Brawler => new UnitInfo(
                UnitType.Brawler,
                "Brawler",
                600,
                1,
                7,
                24,
                false,
                new WalkForwards(8),
                new ChaseBehaviour(8), 
                new AttackBehaviour(230),
                new Vector2Int(1,1),
                MovementLayer.Ground),
            UnitType.Knight => new UnitInfo(
                UnitType.Knight,
                "Knight",
                1000,
                1,
                7,
                24,
                false,
                new WalkForwards(6),
                new ChaseBehaviour(6), 
                new AttackBehaviour(125),
                new Vector2Int(1,1),
                MovementLayer.Ground),
            UnitType.Tower => new UnitInfo(
                UnitType.Tower,
                "Tower",
                2000,
                6,
                6,
                20,
                true,
                new DoNothing(),
                new DoNothing(),
                new RangedAttack(ProjectileType.Arrow),
                new Vector2Int(3,2),
                MovementLayer.Ground,
                true),
            UnitType.Castle => new UnitInfo(
                UnitType.Castle,
                "Castle",
                3200,
                4,
                4,
                24,
                true,
                new DoNothing(),
                new DoNothing(),
                new RangedAttack(ProjectileType.Arrow),
                new Vector2Int(3,2),
                MovementLayer.Ground,
                true),
                UnitType.Giant => new UnitInfo(
                UnitType.Giant,
                "Giant",
                3600,
                1,
                5,
                34,
                false,
                new WalkForwards(6),
                new ChaseBehaviour(4), 
                new AttackBehaviour(175),
                new Vector2Int(2,2),
                MovementLayer.Ground,
                false,
                true),
                UnitType.Archer => new UnitInfo(
                UnitType.Archer,
                "Archer",
                330,
                5,
                12,
                24,
                true,
                new WalkForwards(6),
                new ChaseBehaviour(6), 
                new RangedAttack(ProjectileType.Arrow),
                new Vector2Int(1,1),
                MovementLayer.Ground),
                UnitType.Goblin => new UnitInfo(
                UnitType.Goblin,
                "Goblin",
                210,
                1,
                8,
                14,
                false,
                new WalkForwards(10),
                new ChaseBehaviour(10), 
                new AttackBehaviour(50),
                new Vector2Int(1,1),
                MovementLayer.Ground),
                UnitType.Wizard => new UnitInfo(
                UnitType.Wizard,
                "Wizard",
                700,
                5,
                9,
                32,
                true,
                new WalkForwards(5),
                new ChaseBehaviour(5), 
                new RangedAttack(ProjectileType.WizardBall),
                new Vector2Int(1,1),
                MovementLayer.Ground),
                UnitType.HogRider => new UnitInfo(
                UnitType.HogRider,
                "Hog Rider",
                900,
                1,
                9,
                30,
                false,
                new WalkForwards(15),
                new ChaseBehaviour(15), 
                new AttackBehaviour(170),
                new Vector2Int(1,1),
                MovementLayer.Ground,
                false,
                true),
                UnitType.Barbarian => new UnitInfo(
                UnitType.Barbarian,
                "Barbarian",
                760,
                1,
                9,
                26,
                false,
                new WalkForwards(6),
                new ChaseBehaviour(6),
                new AttackBehaviour(130),
                new Vector2Int(1,1),
                MovementLayer.Ground),
                UnitType.Musketeer => new UnitInfo(
                UnitType.Musketeer,
                "Musketeer",
                620,
                6,
                9,
                30,
                true,
                new WalkForwards(6),
                new ChaseBehaviour(6),
                new RangedAttack(ProjectileType.CannonBall),
                new Vector2Int(1,1),
                MovementLayer.Ground),
            UnitType.Cannon => new UnitInfo(
                UnitType.Cannon,
                "Cannon",
                600,
                9,
                9,
                28,
                true,
                new DoNothing(),
                new DoNothing(),
                new RangedAttack(ProjectileType.CannonBall),
                new Vector2Int(1,1),
                MovementLayer.Ground, true),
                UnitType.MiniPekka => new UnitInfo(
                UnitType.MiniPekka,
                "Mini Pekka",
                1250,
                1,
                13,
                38,
                false,
                new WalkForwards(8),
                new ChaseBehaviour(8),
                new AttackBehaviour(360),
                new Vector2Int(1,1),
                MovementLayer.Ground),
            UnitType.Pekka => new UnitInfo(
                UnitType.Pekka,
                "Pekka",
                2500,
                1,
                13,
                38,
                false,
                new WalkForwards(5),
                new ChaseBehaviour(5),
                new AttackBehaviour(550),
                new Vector2Int(2,2),
                MovementLayer.Ground),
                UnitType.Valkyrie => new UnitInfo(
                UnitType.Valkyrie,
                "Valkyrie",
                1450,
                1,
                9,
                50,
                false,
                new WalkForwards(6),
                new ChaseBehaviour(6),
                new RangedAttack(ProjectileType.Zap),
                new Vector2Int(1,1),
                MovementLayer.Ground),
            UnitType.Skeleton => new UnitInfo(
                UnitType.Skeleton,
                "Skeleton",
                90,
                1,
                6,
                18,
                false,
                new WalkForwards(8),
                new ChaseBehaviour(8),
                new AttackBehaviour(40),
                new Vector2Int(1,1),
                MovementLayer.Ground),
            UnitType.Dragon => new UnitInfo(
                UnitType.Dragon,
                "Baby Dragon",
                850,
                4,
                9,
                26,
                true,
                new WalkForwards(5),
                new ChaseBehaviour(5),
                new RangedAttack(ProjectileType.DragonBall),
                new Vector2Int(1,1),
                MovementLayer.Air),
            UnitType.BabyDragon => new UnitInfo(
                UnitType.BabyDragon,
                "Baby_Dragon",
                850,
                4,
                9,
                26,
                true,
                new WalkForwards(5),
                new ChaseBehaviour(5), 
                new AttackBehaviour(95),
                new Vector2Int(1,1),
                MovementLayer.Air),
                
            _ => throw new ArgumentOutOfRangeException(nameof(unitType), unitType, null)
        };
    }
}
